# SPDX-FileCopyrightText: Copyright Christian Amsüss <chrysn@fsfe.org>, Silano Systems
# SPDX-License-Identifier: MIT OR Apache-2.0

[workspace]
resolver = "3"
members = [
    "hophop",
    "ts-103-636-numbers",
    "ts-103-636-utils",
]

# Not part of the workspace because that doesn't work well with Ariel OS setups (?)
exclude = ["examples", "applications/embedded-pt", "applications/bridge-pt"]

[workspace.package]
license = "MIT OR Apache-2.0"
edition = "2024"
repository = "https://github.com/ariel-os/hophop/"
keywords = ["dect", "nr+"]
categories = ["no-std::no-alloc"]

[patch.crates-io]
# from https://github.com/nrf-rs/nrfxlib-sys/pull/20
nrfxlib-sys = { git = "https://github.com/chrysn-pull-requests/nrfxlib-sys", branch="nrfxlib330" }

[workspace.metadata.release]
sign-tag = true
