# SPDX-FileCopyrightText: Copyright Christian Amsüss <chrysn@fsfe.org>, Silano Systems
# SPDX-License-Identifier: MIT OR Apache-2.0
[package]
name = "hophop"
description = "Exploring DECT-2020 NR+"
version = "0.0.1"
readme = "../README.md"

categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
heapless = { version = "0.9.2", features = ["embedded-io-v0.7"] }

embassy-sync = "0.7.2"
defmt = "1"

nrf-modem = { version = "*", features = ["dect", "nrf9151", "defmt"] }
ts-103-636-numbers = { path = "../ts-103-636-numbers/", features = ["defmt"] }
ts-103-636-utils = { path = "../ts-103-636-utils/", features = ["defmt"] }
static_cell = "2.1.1"
itertools = { version = "0.14.0", default-features = false }
embassy-futures = "0.1.2"

# Once nrf-modem provides the switches to pass this on, we won't need the
# dependency here any more. (Then we can also properly introduce features for
# this rather than just always pulling in everything).
nrfxlib-sys = { version = "*", features = ["dect-mac"] }

[target.'cfg(not(target = "thumbv8m.main-none-eabihf"))'.dependencies]
# We're using box_pool, and while that works on thumbv8m without portable
# atomics, it needs them even on amd64 (which is where all the tests and checks
# and rust-analyzer run, unless we go through greater lengths to make those
# still smooth)
heapless = { version = "0.9.2", features = ["portable-atomic"] }
